import { JobSearchPlatform } from '../types/job.types';

// Platform logo as initials (professional, not emoji)
const platformLogos = {
  topcv: 'TC',
  itviec: 'IT',
  topdev: 'TD',
  vietnamworks: 'VW',
  ybox: 'YB',
  glints: 'GL',
  careerbuilder: 'CB',
  careerviet: 'CV',
  timviecnhanh: 'TVN',
  jobsgo: 'JG',
  vieclam24h: 'V24',
  mywork: 'MW',
  linkedin: 'in',
  indeed: 'IN',
  glassdoor: 'GD',
  // New platforms
  jobstreet: 'JS',
  monster: 'MN',
  simplyhired: 'SH',
  ziprecruiter: 'ZR',
  dice: 'DC',
  stackoverflow: 'SO',
  github: 'GH',
  angel: 'AN',
  remote: 'RM',
  weworkremotely: 'WW',
  flexjobs: 'FJ',
  upwork: 'UP',
  freelancer: 'FL',
  fiverr: 'FV',
  turing: 'TR',
  toptal: 'TT',
  hired: 'HR',
  triplebyte: 'TB',
  wellfound: 'WF',
  builtin: 'BI',
  // More Vietnam platforms
  job123: '123',
  vieclam365: '365',
  viectotnhat: 'VTN',
  hoteljob: 'HJ',
  careerlink: 'CL',
  roberthalf: 'RH',
  manpower: 'MP',
  adecco: 'AD',
  randstad: 'RS',
  hays: 'HY',
  michaelpage: 'MG',
} as const;

// Vietnam Job Platforms - Updated URLs 2024
export const vietnamJobPlatforms: JobSearchPlatform[] = [
  {
    id: 'topcv',
    name: 'TopCV',
    country: 'Vietnam',
    url: 'https://www.topcv.vn',
    logo: platformLogos.topcv,
    description: 'Nền tảng tuyển dụng hàng đầu Việt Nam với hơn 200,000 việc làm',
    searchUrlTemplate: 'https://www.topcv.vn/tim-viec-lam-{keyword}?keyword={keyword}&location={location}',
    priority: 1,
  },
  {
    id: 'itviec',
    name: 'ITviec',
    country: 'Vietnam',
    url: 'https://itviec.com',
    logo: platformLogos.itviec,
    description: 'Nền tảng tuyển dụng IT số 1 Việt Nam',
    searchUrlTemplate: 'https://itviec.com/it-jobs/{keyword}?city={location}',
    priority: 1,
  },
  {
    id: 'topdev',
    name: 'TopDev',
    country: 'Vietnam',
    url: 'https://topdev.vn',
    logo: platformLogos.topdev,
    description: 'Cổng thông tin việc làm IT chuyên nghiệp',
    searchUrlTemplate: 'https://topdev.vn/viec-lam-it?keyword={keyword}&location={location}',
    priority: 1,
  },
  {
    id: 'vietnamworks',
    name: 'VietnamWorks',
    country: 'Vietnam',
    url: 'https://www.vietnamworks.com',
    logo: platformLogos.vietnamworks,
    description: 'Website tuyển dụng uy tín với hơn 100,000 nhà tuyển dụng',
    searchUrlTemplate: 'https://www.vietnamworks.com/viec-lam?q={keyword}&l={location}',
    priority: 1,
  },
  {
    id: 'ybox',
    name: 'Ybox',
    country: 'Vietnam',
    url: 'https://ybox.vn',
    logo: platformLogos.ybox,
    description: 'Nền tảng kết nối nhân tài công nghệ',
    searchUrlTemplate: 'https://ybox.vn/tuyen-dung?keyword={keyword}',
    priority: 2,
  },
  {
    id: 'glints',
    name: 'Glints',
    country: 'Vietnam',
    url: 'https://glints.com/vn',
    logo: platformLogos.glints,
    description: 'Nền tảng tuyển dụng và phát triển sự nghiệp',
    searchUrlTemplate: 'https://glints.com/vn/job-search?keyword={keyword}&country=VN&city={location}',
    priority: 2,
  },
  {
    id: 'careerbuilder',
    name: 'CareerBuilder',
    country: 'Vietnam',
    url: 'https://careerbuilder.vn',
    logo: platformLogos.careerbuilder,
    description: 'Nền tảng tuyển dụng toàn cầu tại Việt Nam',
    searchUrlTemplate: 'https://careerbuilder.vn/viec-lam/{keyword}-k-vi.html',
    priority: 2,
  },
  {
    id: 'careerviet',
    name: 'CareerViet',
    country: 'Vietnam',
    url: 'https://careerviet.vn',
    logo: platformLogos.careerviet,
    description: 'Website tìm việc làm trực tuyến hàng đầu',
    searchUrlTemplate: 'https://careerviet.vn/viec-lam/{keyword}-kw.html',
    priority: 2,
  },
  {
    id: 'timviecnhanh',
    name: 'Tìm Việc Nhanh',
    country: 'Vietnam',
    url: 'https://timviecnhanh.com',
    logo: platformLogos.timviecnhanh,
    description: 'Website tìm việc làm nhanh chóng và hiệu quả',
    searchUrlTemplate: 'https://timviecnhanh.com/tim-kiem-viec-lam?tu-khoa={keyword}&tinh-thanh={location}',
    priority: 3,
  },
  {
    id: 'jobsgo',
    name: 'JobsGO',
    country: 'Vietnam',
    url: 'https://jobsgo.vn',
    logo: platformLogos.jobsgo,
    description: 'Nền tảng việc làm trẻ và năng động',
    searchUrlTemplate: 'https://jobsgo.vn/viec-lam.html?keyword={keyword}&address={location}',
    priority: 3,
  },
  {
    id: 'vieclam24h',
    name: 'ViecLam24h',
    country: 'Vietnam',
    url: 'https://vieclam24h.vn',
    logo: platformLogos.vieclam24h,
    description: 'Tìm việc làm 24/7 với hàng ngàn cơ hội',
    searchUrlTemplate: 'https://vieclam24h.vn/tim-kiem-viec-lam-nhanh?q={keyword}&l={location}',
    priority: 3,
  },
  {
    id: 'mywork',
    name: 'MyWork',
    country: 'Vietnam',
    url: 'https://mywork.com.vn',
    logo: platformLogos.mywork,
    description: 'Giải pháp tuyển dụng thông minh',
    searchUrlTemplate: 'https://mywork.com.vn/tuyen-dung?q={keyword}&l={location}',
    priority: 3,
  },
  {
    id: 'job123',
    name: '123Job',
    country: 'Vietnam',
    url: 'https://123job.vn',
    logo: platformLogos.job123,
    description: 'Trang tìm việc làm phổ biến tại Việt Nam',
    searchUrlTemplate: 'https://123job.vn/tuyen-dung?q={keyword}&location={location}',
    priority: 3,
  },
  {
    id: 'vieclam365',
    name: 'ViecLam365',
    country: 'Vietnam',
    url: 'https://vieclam365.vn',
    logo: platformLogos.vieclam365,
    description: 'Việc làm mới mỗi ngày',
    searchUrlTemplate: 'https://vieclam365.vn/tim-viec-lam?keyword={keyword}&location={location}',
    priority: 4,
  },
  {
    id: 'careerlink',
    name: 'CareerLink',
    country: 'Vietnam',
    url: 'https://careerlink.vn',
    logo: platformLogos.careerlink,
    description: 'Kết nối cơ hội việc làm',
    searchUrlTemplate: 'https://careerlink.vn/tim-viec-lam?keyword={keyword}&location={location}',
    priority: 4,
  },
];

// International Job Platforms
export const internationalJobPlatforms: JobSearchPlatform[] = [
  {
    id: 'linkedin-global',
    name: 'LinkedIn',
    country: 'Global',
    url: 'https://www.linkedin.com',
    logo: platformLogos.linkedin,
    description: 'Global professional networking platform',
    searchUrlTemplate: 'https://www.linkedin.com/jobs/search/?keywords={keyword}&location={location}',
    priority: 1,
  },
  {
    id: 'indeed',
    name: 'Indeed',
    country: 'Global',
    url: 'https://vn.indeed.com',
    logo: platformLogos.indeed,
    description: 'World\'s largest job search engine',
    searchUrlTemplate: 'https://vn.indeed.com/jobs?q={keyword}&l={location}',
    priority: 1,
  },
  {
    id: 'glassdoor',
    name: 'Glassdoor',
    country: 'Global',
    url: 'https://www.glassdoor.com',
    logo: platformLogos.glassdoor,
    description: 'Job search with company reviews and salary insights',
    searchUrlTemplate: 'https://www.glassdoor.com/Job/jobs.htm?sc.keyword={keyword}&locT=N&locId=241',
    priority: 1,
  },
  {
    id: 'jobstreet',
    name: 'JobStreet',
    country: 'Global',
    url: 'https://www.jobstreet.vn',
    logo: platformLogos.jobstreet,
    description: 'Leading job portal in Southeast Asia',
    searchUrlTemplate: 'https://www.jobstreet.vn/viec-lam/{keyword}-jobs',
    priority: 2,
  },
  {
    id: 'monster',
    name: 'Monster',
    country: 'Global',
    url: 'https://www.monster.com',
    logo: platformLogos.monster,
    description: 'One of the largest employment websites',
    searchUrlTemplate: 'https://www.monster.com/jobs/search/?q={keyword}&where={location}',
    priority: 2,
  },
  {
    id: 'stackoverflow',
    name: 'Stack Overflow Jobs',
    country: 'Global',
    url: 'https://stackoverflow.com/jobs',
    logo: platformLogos.stackoverflow,
    description: 'Tech jobs from the largest developer community',
    searchUrlTemplate: 'https://stackoverflow.com/jobs?q={keyword}&l={location}',
    priority: 1,
  },
  {
    id: 'github',
    name: 'GitHub Jobs',
    country: 'Global',
    url: 'https://jobs.github.com',
    logo: platformLogos.github,
    description: 'Developer jobs from GitHub',
    searchUrlTemplate: 'https://www.linkedin.com/jobs/github-jobs?keywords={keyword}',
    priority: 2,
  },
  {
    id: 'wellfound',
    name: 'Wellfound (AngelList)',
    country: 'Global',
    url: 'https://wellfound.com',
    logo: platformLogos.wellfound,
    description: 'Startup jobs and venture capital',
    searchUrlTemplate: 'https://wellfound.com/role/{keyword}',
    priority: 2,
  },
  {
    id: 'remote',
    name: 'Remote.co',
    country: 'Global',
    url: 'https://remote.co',
    logo: platformLogos.remote,
    description: 'Best remote jobs in tech',
    searchUrlTemplate: 'https://remote.co/remote-jobs/search/?search_keywords={keyword}',
    priority: 2,
  },
  {
    id: 'weworkremotely',
    name: 'We Work Remotely',
    country: 'Global',
    url: 'https://weworkremotely.com',
    logo: platformLogos.weworkremotely,
    description: 'Largest remote work community',
    searchUrlTemplate: 'https://weworkremotely.com/remote-jobs/search?term={keyword}',
    priority: 2,
  },
  {
    id: 'dice',
    name: 'Dice',
    country: 'Global',
    url: 'https://www.dice.com',
    logo: platformLogos.dice,
    description: 'Tech-focused career site',
    searchUrlTemplate: 'https://www.dice.com/jobs?q={keyword}&location={location}',
    priority: 2,
  },
  {
    id: 'turing',
    name: 'Turing',
    country: 'Global',
    url: 'https://www.turing.com',
    logo: platformLogos.turing,
    description: 'Remote developer jobs at US companies',
    searchUrlTemplate: 'https://www.turing.com/jobs/{keyword}',
    priority: 2,
  },
  {
    id: 'toptal',
    name: 'Toptal',
    country: 'Global',
    url: 'https://www.toptal.com',
    logo: platformLogos.toptal,
    description: 'Top 3% of freelance talent',
    searchUrlTemplate: 'https://www.toptal.com/developers/{keyword}',
    priority: 2,
  },
  {
    id: 'hired',
    name: 'Hired',
    country: 'Global',
    url: 'https://hired.com',
    logo: platformLogos.hired,
    description: 'Salary-transparent tech jobs',
    searchUrlTemplate: 'https://hired.com/talent?keyword={keyword}',
    priority: 3,
  },
  {
    id: 'builtin',
    name: 'Built In',
    country: 'Global',
    url: 'https://builtin.com',
    logo: platformLogos.builtin,
    description: 'Tech hub job listings',
    searchUrlTemplate: 'https://builtin.com/jobs?search={keyword}',
    priority: 3,
  },
  {
    id: 'flexjobs',
    name: 'FlexJobs',
    country: 'Global',
    url: 'https://www.flexjobs.com',
    logo: platformLogos.flexjobs,
    description: 'Vetted remote and flexible jobs',
    searchUrlTemplate: 'https://www.flexjobs.com/search?search={keyword}&location={location}',
    priority: 3,
  },
  {
    id: 'upwork',
    name: 'Upwork',
    country: 'Global',
    url: 'https://www.upwork.com',
    logo: platformLogos.upwork,
    description: 'Largest freelancing platform',
    searchUrlTemplate: 'https://www.upwork.com/search/jobs/?q={keyword}',
    priority: 3,
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    country: 'Global',
    url: 'https://www.freelancer.com',
    logo: platformLogos.freelancer,
    description: 'Global freelancing marketplace',
    searchUrlTemplate: 'https://www.freelancer.com/jobs/{keyword}',
    priority: 3,
  },
  // Recruitment agencies with strong presence
  {
    id: 'roberthalf',
    name: 'Robert Half',
    country: 'Global',
    url: 'https://www.roberthalf.com',
    logo: platformLogos.roberthalf,
    description: 'Professional staffing agency',
    searchUrlTemplate: 'https://www.roberthalf.com/jobs/all-jobs?keywords={keyword}',
    priority: 4,
  },
  {
    id: 'manpower',
    name: 'ManpowerGroup',
    country: 'Global',
    url: 'https://www.manpower.com',
    logo: platformLogos.manpower,
    description: 'Workforce solutions company',
    searchUrlTemplate: 'https://www.manpower.com/ManpowerUSA/Job-Search-Results/?keywords={keyword}',
    priority: 4,
  },
  {
    id: 'adecco',
    name: 'Adecco',
    country: 'Global',
    url: 'https://www.adecco.com',
    logo: platformLogos.adecco,
    description: 'Global HR solutions provider',
    searchUrlTemplate: 'https://www.adeccousa.com/jobs/search/?k={keyword}',
    priority: 4,
  },
  {
    id: 'hays',
    name: 'Hays',
    country: 'Global',
    url: 'https://www.hays.com',
    logo: platformLogos.hays,
    description: 'Recruiting experts worldwide',
    searchUrlTemplate: 'https://www.hays.com/en/job-search-results/?q={keyword}',
    priority: 4,
  },
  {
    id: 'michaelpage',
    name: 'Michael Page',
    country: 'Global',
    url: 'https://www.michaelpage.com',
    logo: platformLogos.michaelpage,
    description: 'Professional recruitment consultancy',
    searchUrlTemplate: 'https://www.michaelpage.com/jobs/{keyword}',
    priority: 4,
  },
];

export function getPlatformsByCountry(country: string): JobSearchPlatform[] {
  switch (country.toLowerCase()) {
    case 'vietnam':
    case 'vn':
    case 'việt nam':
      return vietnamJobPlatforms;
    default:
      return internationalJobPlatforms;
  }
}

export function getAllPlatforms(): JobSearchPlatform[] {
  return [...vietnamJobPlatforms, ...internationalJobPlatforms];
}

export function getPlatformById(id: string): JobSearchPlatform | undefined {
  return getAllPlatforms().find(platform => platform.id === id);
}

// Helper to convert job level to platform-specific format
export function formatLevelForPlatform(level: string, platformId: string): string {
  const levelMap: Record<string, Record<string, string>> = {
    topcv: {
      intern: 'thuc-tap-sinh',
      fresher: 'moi-tot-nghiep',
      junior: 'nhan-vien',
      middle: 'truong-nhom',
      senior: 'truong-phong',
      manager: 'quan-ly',
      director: 'giam-doc'
    },
    itviec: {
      intern: 'intern',
      fresher: 'fresher',
      junior: 'junior',
      middle: 'middle',
      senior: 'senior',
      manager: 'manager',
      director: 'director'
    },
    topdev: {
      intern: 'intern',
      fresher: 'fresher',
      junior: 'junior',
      middle: 'middle',
      senior: 'senior',
      manager: 'manager',
      director: 'director'
    },
    vietnamworks: {
      intern: 'thuc-tap',
      fresher: 'moi-tot-nghiep',
      junior: 'nhan-vien',
      middle: 'truong-nhom',
      senior: 'chuyen-gia',
      manager: 'quan-ly',
      director: 'giam-doc'
    },
    ybox: {
      intern: 'intern',
      fresher: 'fresher',
      junior: 'junior',
      middle: 'middle',
      senior: 'senior',
      manager: 'manager',
      director: 'director'
    },
    glints: {
      intern: 'INTERNSHIP',
      fresher: 'ENTRY_LEVEL',
      junior: 'ENTRY_LEVEL',
      middle: 'MID_SENIOR_LEVEL',
      senior: 'MID_SENIOR_LEVEL',
      manager: 'MANAGER',
      director: 'DIRECTOR'
    },
    careerbuilder: {
      intern: 'thuc-tap',
      fresher: 'moi-tot-nghiep',
      junior: 'nhan-vien',
      middle: 'quan-ly-cap-trung',
      senior: 'chuyen-gia',
      manager: 'quan-ly',
      director: 'giam-doc'
    },
    careerviet: {
      intern: 'thuc-tap-sinh',
      fresher: 'moi-tot-nghiep',
      junior: 'nhan-vien',
      middle: 'truong-nhom',
      senior: 'chuyen-vien-cap-cao',
      manager: 'quan-ly',
      director: 'giam-doc'
    },
    timviecnhanh: {
      intern: 'thuc-tap',
      fresher: 'fresher',
      junior: 'nhan-vien',
      middle: 'truong-nhom',
      senior: 'senior',
      manager: 'quan-ly',
      director: 'giam-doc'
    },
    jobsgo: {
      intern: 'intern',
      fresher: 'fresher',
      junior: 'junior',
      middle: 'middle',
      senior: 'senior',
      manager: 'manager',
      director: 'director'
    },
    vieclam24h: {
      intern: 'thuc-tap',
      fresher: 'moi-tot-nghiep',
      junior: 'nhan-vien',
      middle: 'truong-nhom',
      senior: 'chuyen-gia',
      manager: 'quan-ly',
      director: 'giam-doc'
    },
    mywork: {
      intern: 'intern',
      fresher: 'fresher',
      junior: 'junior',
      middle: 'middle',
      senior: 'senior',
      manager: 'manager',
      director: 'director'
    },
    linkedin: {
      intern: '1',
      fresher: '2',
      junior: '3',
      middle: '4',
      senior: '5',
      manager: '6',
      director: '7'
    },
    indeed: {
      intern: 'entry_level',
      fresher: 'entry_level',
      junior: 'mid_level',
      middle: 'mid_level',
      senior: 'senior_level',
      manager: 'senior_level',
      director: 'senior_level'
    },
    glassdoor: {
      intern: 'INTERNSHIP',
      fresher: 'ENTRY_LEVEL',
      junior: 'MID_LEVEL',
      middle: 'MID_LEVEL',
      senior: 'SENIOR_LEVEL',
      manager: 'MANAGER',
      director: 'EXECUTIVE'
    }
  };

  return levelMap[platformId]?.[level] || level;
}
